// ec_frontend/src/pages/login/Login.tsx
import { useState, type ReactElement } from "react";
import { useForm, type SubmitHandler } from "react-hook-form";
import styles from "./styles/Login.module.scss";
import { LoginSchema, type Login } from "../../schemas/login.schema";
import { zodResolver } from "@hookform/resolvers/zod";
import axios from "axios";
import { useNavigate } from "react-router-dom";

export default function Login(): ReactElement {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Login>({
    resolver: zodResolver(LoginSchema),
  });
  const [isLoading, setLoading] = useState<boolean>(false);
  const navigate = useNavigate();

  const onSubmit: SubmitHandler<Login> = async (data): Promise<void> => {
    try {
      setLoading(true);
      await axios.post("http://localhost:3000/auth/login", data, {
        withCredentials: true,
      });
      setLoading(false);
      navigate("/");
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <div className={styles.loginContainer}>
        <picture className={styles.loginImageFrame}>
          <img src="/man_on_computer.jpg" className={styles.loginImage} />
        </picture>
        <div className={styles.loginFormWrapper}>
          <div className={styles.formBackground}>
            <picture className={styles.logoFrame}>
              <img src="/logo.png" className={styles.logo} />
            </picture>
            <form
              className={styles.loginForm}
              onSubmit={handleSubmit(onSubmit)}
            >
              <div className={styles.loginInputWrapper}>
                <label id={styles.email}>Email</label>
                <input
                  type="email"
                  placeholder="Digite o seu email"
                  {...register("email", { required: true })}
                />
              </div>
              {errors.email ? (
                <p className={styles.error}>{errors.email.message}</p>
              ) : null}
              <div className={styles.loginInputWrapper}>
                <label>Senha</label>
                <input
                  type="password"
                  placeholder="Digite a sua senha"
                  {...register("password", { required: true })}
                />
              </div>
              {errors.password ? (
                <p className={styles.error}>{errors.password.message}</p>
              ) : null}
              <button
                className={`${styles.submitBtn} ${isLoading ? styles.loading : ""}`}
              >
                {isLoading ? "Enviando..." : "Enviar"}
              </button>
              <p className={styles.forgotPasswordBtn}>esqueci minha senha</p>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}

// ec_admin/src/app/pages/login/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  constructor(
    private readonly httpClient: HttpClient,
    private readonly router: Router,
  ) {}

  onSubmit(form: NgForm): void {
    const { email, password } = form.value;
    this.httpClient
      .post<{
        message: string;
      }>(
        'http://localhost:3000/auth/login',
        { email, password },
        { withCredentials: true },
      )
      .subscribe({
        complete: () => {
          this.router.navigate(['/']);
        },
      });

    form.reset();
  }
}

<body>
  <div class="mainImgWrapper">
    <img src="/laptop.jpg" />
  </div>
  <div class="container">
    <div class="wrapper">
      <div class="imgContainer">
        <div class="imgWrapper">
          <img src="/logo_black.png" />
        </div>
      </div>
      <form #loginForm="ngForm" (submit)="onSubmit(loginForm)">
        <div class="inputWrapper">
          <label for="email">Email</label>
          <input
            type="text"
            name="email"
            ngModel
            placeholder="digite o seu email"
          />
        </div>
        <div class="inputWrapper">
          <label for="email">Senha</label>
          <input
            type="text"
            name="password"
            ngModel
            placeholder="digite a sua senha"
          />
        </div>
        <button>Enviar</button>
      </form>
    </div>
  </div>
</body>
